language: python
python: :- '2.7'
branches:
  only:
  - source
install:
- sudo pip install pelican jinja2 markdown ghp-import
script:
- make publish
deploy:
  provider: pages
  repo: mykonakona/mykonakona.github.io
  target_branch: master
  skip_cleanup: true
  github_token: $GH_TOKEN
  name: $GIT_NAME
  email: $GIT_EMAIL
  local_dir: output
  on:
    branch: source
