language: python
python:
    - "2.7"
branches:
  only:
    - source
install:
    - pip install pelican 
    - pip install jinja2 
    - pip install markdown 
    - pip install ghp-import
script:
    - git clone --depth 1 https://github.com/mykonakona/blue-penguin theme
    - make html
    - make publish
deploy:
  provider: pages
  target_branch: master
  skip_cleanup: true
  github_token: $GH_TOKEN
  name: $GIT_NAME
  email: $GIT_EMAIL
  local_dir: output
  on:
    branch: source
