language: python
python:
    - "3.6"
branches:
  only:
    - source
install:
    - pip install pelican 
    - pip install jinja2 markdown ghp-import beautifulsoup4
script:
    - mkdir output
    - git clone --depth 1 https://github.com/mykonakona/pelican-plugins plugins
    - git clone --depth 1 https://github.com/mykonakona/elegant theme
    - env SITEURL="mykonakona.github.io" make publish
deploy:
  provider: pages
  target_branch: master
  skip_cleanup: true
  github_token: $GH_TOKEN
  name: $GIT_NAME
  email: $GIT_EMAIL
  local_dir: output
  on:
    branch: source
